### ISSUE TITLE
Issue with the Basic installation - while creating HERD web server

### ISSUE THREAD

**Issue by bhargav-b** [FINRAOS/herd-mdl#85] opened 2019-03-21 12:55 UTC
Hi Team,

I am Facing other issue, while creating the Web server with basic installation cloud-formation template. Please find the attached screenshot.
I have modified as per our earlier discussion, as mentioned in https://github.com/FINRAOS/herd-mdl/issues/84

I have set MetastorDBClass to - db.m5.large
Image Id - ami-0ad42f4f66f6c1cc9 - (ap-south-1 region)
Any suggestions please. Thanks in advance.

Regards,
Bhargav
![issue1](https://user-images.githubusercontent.com/30067565/54753301-b283af00-4c06-11e9-85a3-6c75fb31e95c.PNG)

**Comment by kusid** [comment] 2019-03-21 15:09
Hello Bhargav, based on the screenshot you posted - it looks like an issue with AWS' parameter store. Could you try rebuilding your stack one more time and let us know if this issue is persistent?

**Comment by bhargav-b** [comment] 2019-03-21 16:13
Hello @kusid, sure will run it again and update you. thank you.

**Comment by bhargav-b** [comment] 2019-03-21 16:52
I am facing a different issue now :(. Please find the attached screenshot
![issue2](https://user-images.githubusercontent.com/30067565/54769718-cee41380-4c27-11e9-914e-fc1b88071c0c.PNG)
.

**Comment by kusid** [comment] 2019-03-21 16:59
Hi Bhargav, could you send us a screenshot of the events from the stack which originally had issues? For example; in this case, could you send us a screenshot from the failing prerequisites primary stack? You'll find it under the list of deleted stacks when it completes rollback.

**Comment by rongwang0930** [comment] 2019-03-21 17:18
small note, if you are using same instancename, please make sure  previous failing stack is deleted before bringing up new stack, otherwise, you will get error for duplicate resource creation.

**Comment by bhargav-b** [comment] 2019-03-21 17:30
Hello @kusid ,I did nt get you exactly what is teh expected screenshot here. But I am attaching one as per my understanding.
@rongwang0930 , yeah I am creating the stack trace when the previous stack deleted only.

**Comment by bhargav-b** [comment] 2019-03-21 17:32
![issue3](https://user-images.githubusercontent.com/30067565/54772428-54b68d80-4c2d-11e9-8063-26d0a588ff40.PNG)

**Comment by bhargav-b** [comment] 2019-03-22 09:28
Hello Team,

Today I am facing this error. Please find the attached screenshot.

Regards,
Bhargav
![issue4](https://user-images.githubusercontent.com/30067565/54813172-faf8a680-4cb2-11e9-8123-c0f5ee078465.png)

**Comment by bhargav-b** [comment] 2019-03-22 11:13
One more screenshot, where I run the script again, by updating the value of "Timeout" to 600 in basic.main "installMDL.yaml" file, thinking that the earlier timeout issue might be because of Timeout session.

![issue5](https://user-images.githubusercontent.com/30067565/54819341-9db82180-4cc1-11e9-8008-e5cd310f390f.png)

**Comment by rongwang0930** [comment] 2019-03-22 13:07
its comming from the codedeploy, can you go to the codedeploy console, find the herd codedeploy, send us a screenshot of herd codedeploy failure detail?

**Comment by bhargav-b** [comment] 2019-03-22 13:13
It has rolled-back automatically, hence we couldnt find the herd codedeploy in our codedeploy console. We will try to run the build again and try to find it. Thank you.

**Comment by rongwang0930** [comment] 2019-03-22 13:15
you can rerun with rollback on failure disabled .

**Comment by bhargav-b** [comment] 2019-03-22 13:21
okay. How to disable the failure/rollback. We have searched in the Yaml file and as well as in the console, but couldn't find any. Thanks.

**Comment by rongwang0930** [comment] 2019-03-22 13:35
there should be an checkbox for you when you are creating stack using cloudformation from aws console.

**Comment by bhargav-b** [comment] 2019-03-22 13:40
okay, got it. thanks.

**Comment by bhargav-b** [comment] 2019-03-22 17:47
Now, it is not coming upto that point :).. will share the screenshot, once it is done. Thank you.

**Comment by bhargav-b** [comment] 2019-03-24 12:37
We are facing some different issue. It seems to be like some issue with S3 bucket conflict issue as per my understanding. We have disabled the roll-back to get the logs and debugging.

Please find the attached screen-shot. Thanks in advance.
![issue6](https://user-images.githubusercontent.com/30067565/54879499-9b8bc980-4e5f-11e9-88eb-4f30628fc100.PNG)

**Comment by bhargav-b** [comment] 2019-03-25 07:45
We have run the script again today with another User, and here are the screenshots which might  be helpful. Thank you.
![issue1](https://user-images.githubusercontent.com/30067565/54902643-02f95600-4f00-11e9-9d77-ab8dab9bcfc3.png)
![issue2](https://user-images.githubusercontent.com/30067565/54902644-02f95600-4f00-11e9-8188-21df4b723eac.png)
![issue3](https://user-images.githubusercontent.com/30067565/54902645-02f95600-4f00-11e9-9b16-0a55886bcd0d.png)
![issue4](https://user-images.githubusercontent.com/30067565/54902646-0391ec80-4f00-11e9-98f0-8a8c6c647fbf.png)
![issue5](https://user-images.githubusercontent.com/30067565/54902647-0391ec80-4f00-11e9-932a-be22b3bc03d8.png)

**Comment by bhargav-b** [comment] 2019-03-25 18:14
Hello team, any updates on this please.

Thanks in advance.

**Comment by bhargav-b** [comment] 2019-03-27 16:22
Team, any update on this please. Today I have run it again, and facing the same issue. We really need your assistance . TIA

**Comment by kusid** [comment] 2019-03-27 16:42
Hi Bhargav, apologies for not getting back to you earlier. 
Let's tackle these issues one at a time. Your first issue is probably related to the server deployment role not having terminate permissions; however, that sounds very unusual since we explicitly add that action in its policy when creating that role. Do you mind double-checking the deployment role? It's name is formatted like so: `APP_${MDLInstanceName}_Deployment`.

**Comment by rongwang0930** [comment] 2019-03-27 16:49
@bhargav-b I'm looking at it now, looks like there is something for the elastic search creation, at this time herd should be ready already.
1). first in your screenshot, i saw elasticsearch codedeploy failed too, this is not from the same deploy, right?
2). can you try to hit this url and let me the results
http://${herdLoadBalancerDNSName}/herd-app/rest/searchIndexes/${indexName}
**Note**: ${herdLoadBalancerDNSName} is your herd alb dns, ${indexName} is the failed index name(it's bdef_1553xxx in your latest screenshot )
you should be able to get these two variables in the latest codedeploy log,

**Comment by rongwang0930** [comment] 2019-03-27 16:53
can you please attach your full cloudwatch log for the latest herd codedeploy?
you should be able to find necessary information in this page https://finraos.github.io/herd-mdl/docs.html
Inside the **Administration** left tab, there is the part named **"Logs inside customized stack log group"**

**Comment by bhargav-b** [comment] 2019-03-28 06:24
Hi @kusid , hey no probs. We have triggered the build again yesterday, and were able to get to the webserver page. And the issue with regards to Deployment has been resolved it seems. Thank you for your reply. The only issue we are facing now is, web server installation.

**Comment by bhargav-b** [comment] 2019-03-28 06:27
Hi @rongwang0930 , thanks for your reply.
The deploy regards to elastic search is from same deploy. I will try to hit the URL which you are saying, and will share the logs too soon, as we just ran the build again. And also, we will share the full Code deploy logs soon. Thank you.

**Comment by bhargav-b** [comment] 2019-03-28 09:10
I tried to hit this URL, http://${herdLoadBalancerDNSName}/herd-app/rest/searchIndexes/${indexName}..and got this..
![issue7](https://user-images.githubusercontent.com/30067565/55144711-70f38680-5167-11e9-9f64-cd04fb7d0ebc.PNG)

**Comment by bhargav-b** [comment] 2019-03-28 10:35
Hi @rongwang0930 , Please find the logs attached. Thank you in advance.
[CodeDeploy Deployments.txt](https://github.com/FINRAOS/herd-mdl/files/3017442/CodeDeploy.Deployments.txt)
[ES-codedeploy-updater-log.txt](https://github.com/FINRAOS/herd-mdl/files/3017443/ES-codedeploy-updater-log.txt)
[ES-codedeploy-agent-log.txt](https://github.com/FINRAOS/herd-mdl/files/3017444/ES-codedeploy-agent-log.txt)
[codedeploy-updater-log.txt](https://github.com/FINRAOS/herd-mdl/files/3017445/codedeploy-updater-log.txt)
[codedeploy-agent-log.txt](https://github.com/FINRAOS/herd-mdl/files/3017446/codedeploy-agent-log.txt)

**Comment by rongwang0930** [comment] 2019-03-28 12:29
if the elaticserch fail, you should not get to the herd step, can you check if the elasticsearch codedeploy fail this time? if so please do this,
1).please check the elasticseach cloudformation console, make sure no error here
2). check elasticserch domain service from elasticsearch console page, make sure the service is up.
3). did you have auth enabled in your stack? if so, can hit the url with correct credential, ler me the result.

we'll debug further if both 1&2 are fine.

**Comment by rongwang0930** [comment] 2019-03-28 12:36
@bhargav-b 
just realize elasticsearch codedeploy may not be required for us, we use  aws elasticsearch domain service instead now, @kusid correct me if I'm wrong.
@bhargav-b can you do two things.
1). please check the elasticseach cloudformation console, make sure no error here
2). check elasticserch domain service from elasticsearch console page, make sure the service is up.
let me know if there are any error in 1 or 2, we'll debug further.

**Comment by bhargav-b** [comment] 2019-03-28 12:56
@rongwang0930 How can I check the #2 one please..

**Comment by bhargav-b** [comment] 2019-03-28 13:01
We didnt found any errors in elastic search (regards to #1st one). Thank you.

**Comment by rongwang0930** [comment] 2019-03-28 14:21
> @rongwang0930 How can I check the #2 one please..
it's a aws service, type elastic search in the aws service search, you should be able to find the console

**Comment by rongwang0930** [comment] 2019-03-28 15:10
@bhargav-b I've sent you a list of thins to check on github slack channel, please take a look, in our github homepage, there is icon named "chat on gitter"

**Comment by bhargav-b** [comment] 2019-03-28 15:45
@rongwang0930  ok. We have just triggered the build again, will share the Elastic Search 

> > @rongwang0930 How can I check the #2 one please..
> > it's a aws service, type elastic search in the aws service search, you should be able to find the console

@rongwang0930  ok. We have just triggered the build again, will share the Elastic Search in some time.

**Comment by bhargav-b** [comment] 2019-03-28 15:46
> @bhargav-b I've sent you a list of thins to check on github slack channel, please take a look, in our github homepage, there is icon named "chat on gitter"

ok will check and let you know.

**Comment by bhargav-b** [comment] 2019-03-28 17:53
Now, the build failed at ElasticSearch it self. :( attaching the screenshots..
![issue10](https://user-images.githubusercontent.com/30067565/55180883-7f19c500-51b0-11e9-9cf1-71fc6838f4d4.PNG)

**Comment by bhargav-b** [comment] 2019-03-28 17:54
Elastic search domain is also seems to be in red. Please find the attached screenshots.
![issue9](https://user-images.githubusercontent.com/30067565/55180948-9b1d6680-51b0-11e9-9ea3-1ddd9b9dbb36.PNG)
![issue8](https://user-images.githubusercontent.com/30067565/55180949-9b1d6680-51b0-11e9-9207-675520ca44ae.PNG)

**Comment by kusid** [comment] 2019-11-08 21:41
Closing as unable to reproduce. @bhargav-b we're pushing out a new release, could you try that and let us know if you still need assistance? Thanks.

**Closed** 2019-11-08 21:40 UTC
